- dbt/include/impala/macros/adapters.sql
- dbt/include/impala/macros/incremental.sql
incremental support - strategy: append, insert_overwrite; onschema_change: fail, ignore
not supported strategy: merge, delete_overwrite; onschema_change: append_new_columns, sync_new_columns
not supported: unique_key
Ticket (internal JIRA):
https://jira.cloudera.com/browse/DBT-38
https://jira.cloudera.com/browse/DBT-39
https://jira.cloudera.com/browse/DBT-48
https://jira.cloudera.com/browse/DBT-49
Testplan:
1. Basic dependencies need to be installed. These are mentioned in README.txt
2. Build and install the dbt-impala adapter using:
python3 setup.py install
3. Create a template dbt project using following:
dbt init
4. Edit $HOME/.dbt/profiles.yml so that it looks similar to:
demo_dbt:
outputs:
dev_impala:
type: impala
host: localhost
port: 21050
dbname: s3test
schema: s3test
target: …
> incremental support for dbt impala 

- dbt/adapters/impala/connections.py
(Internal Ticket): https://jira.cloudera.com/browse/DBT-21
Testplan:
1. Basic dependencies need to be installed. These are mentioned in README.md
2. Build and install the dbt-impala adapter using:
python3 setup.py install
3. Create a template dbt project using following:
dbt init
4. Ensure kerberos is initilized and relevant libraries properly installed - depending on your OS
5. Edit $HOME/.dbt/profiles.yml so that it looks similar to:
demo_dbt:
outputs:
dev_impala_kerberos:
type: impala
host: <hostname>
port: <port>
auth_type: GSSAPI
kerberos_service_name: <kerberos service name>
use_http_transport: true
use_ssl: true
dbname: s3test
schema: s3test
target: dev_impala_kerberos
6. In the dbt project generated in step (2), run the following, which should succeed if local instance of Impala …
> kerberos support for connecting to impala instance

- setup.py
remove pinned dependency of dbt-core==1.0.1 in setup.py
Testplan:
1. Update dbt-core dependency to 1.0.4 (pip3 install --upgrade dbt-core), the current release version
2. From a dbt_demo project (https://github.infra.cloudera.com/abrown/dbt_demo) check:
dbt debug (connection)
dbt seed (seeds)
dbt run (models)
dbt docs generate (generate docs)
dbt docs serve (start a browser with generated docs)
3. All commands should execute without error
4. Optional:
dbt tests (this will check if dbt tests is running)
> remove pinned dependency of dbt-core==1.0.1 in setup.py

- dbt/include/impala/macros/adapters.sql
Internal Ticket: https://jira.cloudera.com/browse/DBT-75
Testplan:
1. Basic dependencies need to be installed. These are mentioned in README.txt
2. Build and install the dbt-impala adapter using:
python3 setup.py install
3. Create a template dbt project using following:
dbt init
4. Edit $HOME/.dbt/profiles.yml so that it looks similar to:
demo_dbt:
outputs:
dev_impala:
type: impala
host: localhost
port: 21050
dbname: s3test
schema: s3test
target: dev_impala
5. In the dbt project generated in step (2), run the following, which should succeed if local instance of Impala is up:
dbt debug (check connection)
6. Write a model similar to:
{{
config(
materialized='table',
external=true
)
}}
select * from {{ source('s3test', 'census') }}
The config option external=true creates an external table. …
> support EXTERNAL clause with table materialization

- dbt/include/impala/macros/adapters.sql
A solution for issue where view, table are not distinguished in the list_relations macro as a result drop_relation and rename_relation would fail for view.
GH Issue: https://github.com/cloudera/dbt-impala/issues/16
Internal Ticket: https://jira.cloudera.com/browse/DBT-79
Test plan: Follow the GH issue for test case.
> solution for: schema change of model with VIEW materialisation runs ALTER TABLE and fails

- dbt/adapters/impala/__version__.py
- setup.py
Reverts cloudera/dbt-impala#22
pip renames 1.0.4-1 to 1.0.4.post1 which breaks dbt --version 
Also, using .post releases is discouraged for changes that materially affect the code
> Revert "Update setup.py for 1.0.4b release"

- dbt/adapters/impala/__version__.py
- setup.py
Updating versions to 1.0.5rc2
Using https://github.com/sdairs/dbt-impala-demo to test against dbt-core==1.0.5rc2
> Bump version to 1.0.5rc2

- dbt/include/impala/macros/adapters.sql
Restructure relation macros to better handle errors, improving consistency of getting the relation types.
Description of the issue can be found in #23 and #26 
Test plan:
The test cases are available in GH Issue #23  and Issue #26
> #23 #26 Improve error handling for relation macros

- dbt/include/impala/macros/incremental.sql
- dbt/include/impala/macros/insertoverwrite.sql
Issue Summary: For incremental models, when using insert_overwrite mode along with partition clause, doesn't work as expected.
1. The code did not handle the partition clause correctly with insert statement that was being generated.
2. The code needed to use insert overwrite statement along with partition clause for the correct behaviour.
Test Plan:
1. Create a dbt model similar to (inc_over_model.sql):
{{
config(
materialized='incremental',
on_schema_change='ignore',
partition_by=['some_date'],
file_format='parquet',
incremental_strategy='insert_overwrite',
)
}}
select id,name,float_value,bool_value,updated_at,some_date from {{ ref('datetime_test') }}
{% if is_incremental() %}
where updated_at > (select max(updated_at) from {{ this }})
{% endif %}
2. Run this model using:
dbt run …
> Issue Summary: For incremental models, when using insert_overwrite mode along with partition clause, doesn't work as expected

- dbt/adapters/impala/__version__.py
- setup.py
This PR for aligning version number of adapter with that of the targeted dbt-core (1.1.0) release.
> * bump version number to 1.1.0 to align with dbt-core versioning

- dbt/adapters/impala/impl.py
- dbt/adapters/impala/relation.py
- dbt/include/impala/macros/adapters.sql
Modify impala__list_relations_without_caching macro implementation to query each object type to return the object type (table / view)
Test plan:
1. Merge PR https://github.com/cloudera/dbt-impala/pull/33 to ensure new adpater test framework code is present.
2. Ensure pytest is installed
2. Run : python3 -m pytest tests/functional -k 'TestSimpleMaterializationsImpala' - This test should succeed.
> list_relations_without_caching should now query and return object type for each object in schema

- dbt/include/impala/macros/insertoverwrite.sql
Internal Issue Ticket: https://jira.cloudera.com/projects/DBT/issues/DBT-130
Test plan:
Use the Impala demo project https://github.com/cloudera/dbt-impala-example
Generate the first set of fake data, and then run the models using dbt run.
Next generate the second set of fake data, and then run the models using dbt run.
The second run should terminate without any error, updating the the incremental model.
Synopsis:
For model definitions that define partition_by clause with a string, the adapter wrongly generates the insert overwrite statement,
resulting in an error being thrown by impala.
An example model configuration that will generate error (before applying this PR):
{{
config(
materialized='incremental',
partition_by='report_date'
)
}}
An example model configuration that will not …
> dbt run for incremental models fail on second run

- setup.py
This dependency is added as this has the upstream fix https://github.com/cloudera/impyla/issues/487 and is more stable in Cloudera CML environment.
> update impyla dependency to 0.18a5

- setup.py
add functions from dbt-spark repo in setup.py to enable automatic dbt-core requirements based on major and minor version of the dbt-impala adapter
> enable automatic dbt-core version requirements in setup.py

- dbt/include/impala/macros/apply_grants.sql
add macros to support copy_grants and support_multiple_grantees_per_dcl_statement
These macros are needed as a part of dbt-core=1.2 migration
> add supporting macros for grants 

- dbt/include/impala/macros/adapters.sql
Synopsis:
The swappable functional test checks what happens when user changes materialization from view to table (or the other way round).
Resolution:
Instead of querying warehouse for object type, drop view and table objects in the rename_relation macro before performing a rename.
Testplan:
python3 -m pytest tests/functional -k 'TestSimpleMaterializationsImpala'
(swappable test of view-table should succeed, swappable test for incremental materialization will still fail)
> Fix an issue that caused swappable test (view<->table) fail.

- dbt/include/impala/macros/adapters.sql
Add a macro to ensure that the database is always None, so that double qualified names are not generated.
This is required as in Impala there is no separate database name, so object names are qualified merely as schema.object_name and not database.schema.object_name
This macro merely ensures that the database is always None, ensuring that the fully qualified name generated by dbt is schema.object_name irrespective of ImpalaIncludePolicy
> Add macro generate_database_name always returning None

- dbt/include/impala/macros/adapters.sql
- dbt/include/impala/macros/incremental.sql
Internal Ticket: https://jira.cloudera.com/projects/DBT/issues/DBT-226
Synopsis:
The swappable functional test checks what happens when user changes materialization from view to table for incremental models (or the other way round).
Resolution:
Instead of querying warehouse for object type, drop view and table objects in the drop_relation macro. Modify incremental flow to call this macro for every object (target or intermediate) that is created.
Testplan:
python3 -m pytest tests/functional -k 'TestSimpleMaterializationsImpala'
(This functional test should fully succeed)
> Fix for swappable materialization test

- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/connections.py
A sample query execution record would look like:
[0m10:44:37.345522 [debug] [Thread-78 ]: Tracker adapter: Sending Event [{"data": {"id": "dbt_impala_start_query", "unique_hash": "0d957f2dd9707f9eea2aa91a24858cb4", "sql": "/* {\"app\": \"dbt\", \"dbt_version\": \"1.2.1\", \"profile_name\": \"dbtdemo\", \"target_name\": \"dev_impala_local\", \"node_id\": \"model.dbtdemo.my_second_dbt_model\"} */\n\n    show tables in dbtdemo like \"my_second_dbt_model__dbt_tmp\"\n  "}}]
^[[0m10:44:37.345685 [debug] [Thread-19 ]: On model.dbtdemo.my_second_dbt_model: /* {"app": "dbt", "dbt_version": "1.2.1", "profile_name": "dbtdemo", "target_name": "dev_impala_local", "node_id": "model.dbtdemo.my_second_dbt_model"} */
show tables in dbtdemo like "my_second_dbt_model__dbt_tmp"
^[[0m10:44:37.357413 [debug] …
> instrument query execution

- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/connections.py
Testplan
a) create a sample dbt project
b) edit any model file to introduce error in the sql statement
c) execute dbt run. dbt should fail normally, for instance: 
ganesh.venkateshwara@MacBook-Pro dbtdemo % dbt run 11:07:39  Running with dbt=1.1.2
11:07:40  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 191 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics 11:07:40
11:07:40  Concurrency: 4 threads (target='dev_impala_local') 11:07:40
11:07:40  1 of 3 START table model dbtdemo.my_first_dbt_model ............................ [RUN] 11:10:02  1 of 3 OK created table model dbtdemo.my_first_dbt_model ....................... [OK in 141.63s] 11:10:02  2 of 3 START incremental model dbtdemo.my_incremental_model .................... [RUN] 11:10:02  3 of 3 START view model …
> capture errors in query execution

- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/relation.py
- dbt/include/impala/macros/incremental.sql
instrument model usage.
track two events:
1) model is accessed
7:52:35.778463 [debug] [Thread-133]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_impala_model_access", "model_name": "dbtdemo.my_second_dbt_model", "model_type": "view", "python_version": "3.9.12", "system": "Darwin", "machine": "arm64", "platform": "macOS-12.6-arm64-arm-64bit", "dbt_version": "1.1.2", "dbt_adapter": "impala-1.1.2", "id": "17b4de51-0125-4323-a195-2d41d0f702a7", "unique_host_hash": "a80df3703d95f6c576ac4c680a231390", "unique_user_hash": "6444baa7f3e0fa703845a1ca38c973b6", "unique_session_hash": "2415b7a36210b424b8c164d8707ff6ff", "project_name": "dbtdemo", "target_name": "dev_impala_ldap", "no_of_threads": 1}}]
2) incremental model is created
07:49:55.442522 [debug] [Thread-79 ]: Tracker …
> instrument model usage.

- dbt/adapters/impala/connections.py
Internal ticket: https://jira.cloudera.com/browse/DBT-398
The error printed seems to be generic, so adding
code to identity the failure from Impala connection.
Test plan:
* Move into a dbt impala project and install dbt-impala from this git repo
* Add profile details in your home dbt file like below, 
dbt_impala_demo:
outputs:
dev:
auth_type: ldap
host: {}
http_path: {}
password: {}
port: 443
schema: dbt_impala_demo
dbname: dbt_impala_demo
threads: 4
type: impala
use_http_transport: true
use_ssl: true
user: {}
target: dev
* Update with wrong hostname or wrong user credentials
* run > dbt debug, and you should see the type of error in the console
* Add below snowplow configs to your .env if you face any snowplow error   
SNOWPLOW_ENDPOINT=https://dcevents.cldrteam.datacoral.io/cldrteam/apie …
> Add http error identification for credentials and hostname errors

- dbt/adapters/impala/cloudera_tracking.py
* In some environemnts such as pytest for running functional tests, active_user is not available and causes a runtime exception. This PR simiply checks if a valid active_user object is available before attempting to use it.
* Addresses a data format issue with the data being sent for instrumentation.
> fix issues with cloudera_tracking

- dbt/include/impala/macros/utils/concat.sql
- dbt/include/impala/macros/utils/escape_single_quotes.sql
- dbt/include/impala/macros/utils/position.sql
- dbt/include/impala/macros/utils/split_part.sql
- tests/functional/adapter/test_utils.py
* add tests related to cross db string macros
* implement macros that are failing: concat escape_single_quotes position split_part
Run the functional test:
python -m pytest tests/functional/adapter/test_utils.py 
All tests should succeed.
> cross_db macros - strings

- dbt/include/impala/macros/utils/listagg.sql
- tests/functional/adapter/test_utils.py
* add listagg macro
* add tests for list_agg, remove data points not supported by impala
- order_by
- limit_num
Run tests using:
python -m pytest tests/functional/adapter/test_utils.py -k '[test-class-name]'
> list related cross-db macro

- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/connections.py
Recycle cursor object for a connection.
Earlier implementation opened a new cursor object for every sql that is executed. This is fine for most part, but when using pre-hooks with SET commands in Impala, the cursor context is lost resulting in the SET parameters not being available or enforced for subsequent queries being executed. 
One instance where the SET command is needed is for setting the request pool. To test this create a request pool for impala (say root.small), and then create a model with pre-hook as follows:
<pre>
{{
config(
pre_hook=["set request_pool='root.small'"],
materialized='table'
)
}}
with source_data as (
select 1 as id
union all
select null as id
)
select *
from source_data;
</pre>
Next run the model as follows:
dbt run --select …
> recycle cursor object for a connection

- dbt/adapters/impala/impl.py
- dbt/include/impala/macros/apply_grants.sql
- dbt/include/impala/macros/incremental.sql
- tests/functional/adapter/test_grants.py
Describe your changes:
Support for grant macros
Testing procedure:
1. set DBT_TEST_USER1/2/3 user variable with ware house users that can run grant command
2. Run the functional test using:
python -m pytest tests/functional/adapter/test_grants.py
Currently only one test is supported: TestModelGrantsImpala
> support grants

- dbt/adapters/impala/impl.py
- dbt/include/impala/macros/incremental.sql
* set default strategy as 'append'
* add valid_incremental_strategies adapter method
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestIncrementalImpala'
collected 11 items / 10 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_pytest/config …
> refactoring incremental - 1

- dbt/include/impala/macros/incremental.sql
add get_incremental_default_sql macro
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestIncrementalImpala'
collected 11 items / 10 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_pytest/config/__init__.py:1253: PytestConfigWarning: …
> refactoring incremental - 2

- tests/functional/adapter/test_basic.py
adds a new test TestBaseIncrementalNotSchemaChange for dbt-core==1.3
Test result:
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestBaseIncrementalNotSchemaChange'
collected 12 items / 11 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_pyt …
> add new test TestBaseIncrementalNotSchemaChange

- tests/functional/adapter/test_data_types.py
Add datatype tests.
Test result:
<pre>
(dev-dbt-impala) ganesh.venkateshwara@ganesh dbt-impala % python -m pytest tests/functional/adapter/test_data_types.py                                             
==================================================================================== test session starts =====================================================================================
collected 6 items                                                                                                                                                                            
tests/functional/adapter/test_data_types.py ...... …
> add datatype test

- tests/functional/adapter/test_utils.py
<pre>
python -m pytest tests/functional/adapter/test_utils.py -k 'TestCurrentTimestamp'
collected 22 items / 20 deselected / 2 selected
tests/functional/adapter/test_utils.py ..                                [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_pytest/config/__init__.py:1253: PytestConfigWarning: Unknown config option: env_files
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============ 2 passed, 20 deselected, 1 warning in 82.08s (0:01:22) ============
</pre>
> add test BaseCurrentTimestampNaive

- dbt/include/impala/macros/utils/array_append.sql
- dbt/include/impala/macros/utils/array_concat.sql
- dbt/include/impala/macros/utils/array_construct.sql
- dbt/include/impala/macros/utils/datediff.sql
Array functions are not supported in Impala, and hence are marked to throw an Not implemented exception when called. 
Also fix typo in error message.
> Mark utils functions that are not supported in Impala

- tests/functional/adapter/test_concurrency.py
Add new test TestConcurrencyImpala.
Test run:
<pre>
python -m pytest tests/functional/adapter/test_concurrency.py
collected 1 item
tests/functional/adapter/test_concurrency.py .                           [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_pytest/config/__init__.py:1253: PytestConfigWarning: Unknown config option: env_files
-- Docs: …
> add new test TestConcurrencyImpala

- dbt/include/impala/macros/incremental.sql
restructure incremental implementation to follow default implementation
Test 1 (functional test)
<pre>
python -m pytest tests/functional/adapter/test_basic.py -k 'TestIncrementalImpala'
collected 11 items / 10 deselected / 1 selected
tests/functional/adapter/test_basic.py .                                 [100%]
/Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/lib/python3.9/site-packages/_p …
> restructure incremental implementation to follow default implementation

- dbt/adapters/impala/cloudera_tracking.py
split dbt_adapter field in instrumentation to dbt_adapter_type and dbt_adapter_version
Test Result:
{'data': '{"event_type": "dbt_impala_close", "connection_state": "closed", "elapsed_time": "0.00", "auth": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "0deb7d68-d2fd-488c-b4eb-3e72fa99856b", "unique_host_hash": "a80df3703d95f6c576ac4c680a231390", "unique_user_hash": "e8a5d78ea632435d797d3d58df650872", "unique_session_hash": "b0828c493ae03270080489765f1a814d", "python_version": "3.10.7", "system": "Darwin", "machine": "arm64", "platform": "macOS-13.0.1-arm64-arm-64bit", "dbt_version": "1.3.1", **"dbt_adapter_type": "impala", "dbt_adapter_version": "1.3.0"**, "dbt_deployment_env": {}, …
> split dbt_adapter field in instrumentation to dbt_adapter_type and dbt_adapter_version

- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/connections.py
- dbt/adapters/impala/impl.py
- dbt/adapters/impala/relation.py
* modify populate_unique_ids to provide optional userkey
* refactor warehouse key, add event type enums
* use the refactored tracking lib: event type, warehouse version 
Using dbt debug, a sample tacking payload in dbt.logs:
<pre>
14:39:42.232590 [debug] [MainThread]: Tracker adapter: Sending Event {'data': '{"event_type": "close", "connection_state": "closed", "elapsed_time": "0.00", "auth": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "de0426cc-1ef7-4b5e-9b21-10509264ebae", "unique_host_hash": "a80df3703d95f6c576ac4c680a231390", "unique_user_hash": "e8a5d78ea632435d797d3d58df650872", "unique_session_hash": "81adc06a71ea48ebb780a9a8e78c5fcf", "python_version": "3.9.12", "system": …
> refactor cloudera_tracking: event type as enums, optional userkey, warehouse version fetch

- dbt/adapters/impala/connections.py
- setup.py
Add support for [plain authorization](https://github.com/cloudera/impyla/blob/0f2be72e31feab9cc6d91b44dc873af306bcb97a/impala/dbapi.py#L71) & fix minor issue with requirements on Windows.
Issue #140 
Tested connection to Impala server using plain authorization, which worked. I can provide screenshots upon request.
> Plain authorization support

- dbt/adapters/impala/.env
- dbt/include/impala/macros/adapters.sql
Hello Team, 
We have added the following code changes
- ability to create iceberg table e.g stored by iceberg will be inserted if is_iceberg is set to true
- By passing the tbl_properties we can choose V1 or V2 iceberg table `tbl_properties="('format-version'='2')"`
https://jira.cloudera.com/browse/DBT-671 
- [Yes ] I have performed a self-review of my code
- [ Notsure ] I have formatted my added/modified code to follow pep-8 standards
- [ Yes ] I have checked suggestions from python linter to make sure code is of good quality.
> ability to create Iceberg V1 and V2 tables

- .gitignore
- CONTRIBUTING.md
- README.md
- pytest.ini
- test.env.example
- tests/conftest.py
- tests/functional/adapter/test_basic.py
There are two changes: 
1. Add the capability to run the integration test against the specific endpoint/cluster like cdh_endpoint vs dwx_endpoint 
2. Add a readme section for functional tests
3. To stabilize the broken branch tests, skip the basic_tests eg https://gist.github.com/niteshy/0bb490cc4bf4ec9288d694bcffe9b5a5 
https://jira.cloudera.com/browse/DBT-672 
https://gist.github.com/niteshy/fef35fc57ad63b16892a516d5443b823 
https://gist.github.com/niteshy/4df70995314d0dde81837c8352620d05
- [Y] I have performed a self-review of my code
- [] I have formatted my added/modified code to follow pep-8 standards
- [] I have checked suggestions from python linter to make sure code is of good quality.
> DBT-672: Setup for the integration tests to be triggered against a given environment or endpoint

- dbt/adapters/impala/impl.py
- tests/conftest.py
- tests/functional/adapter/test_basic.py
If a table is not found in the path, impala throws a "Could not resolve path" error. Catching the error and returning empty array in get_columns_in_relation()
https://jira.cloudera.com/browse/DBT-675
https://gist.github.com/vamshikolanu/30ed615ad5e79c41e0a600f190c71abc
> DBT-675: Catch "Could not resolve path" error if table is not found.

- tests/functional/adapter/test_utils.py
test_utils.py has broken test TestBoolOr because column named `key` is a reserve keywords in impala. 
Hence, rename the column to key_column  
https://jira.cloudera.com/browse/DBT-680
https://gist.github.com/niteshy/0bd9ce5425c8b964afdf1bb17ec1e10c
> DBT-680: Fixing the functional test for utils, key is reserve keywords

- dbt/include/impala/macros/adapters.sql
- tests/functional/adapter/test_formats.py
- tests/functional/adapter/test_icerberg_format.py
Adding function tests for iceberg table format that was landed as part of https://github.com/cloudera/dbt-impala/pull/149. 
Please note that for iceberg check_relations_equal util is not working. Hence removing this check as part of unit tests. 
Here is the upstream impala ticket for the same: https://issues.apache.org/jira/browse/IMPALA-12097
DBT ticket to include check_relations_equal util for iceberg unit tests:  https://jira.cloudera.com/browse/DBT-685
https://jira.cloudera.com/browse/DBT-684
https://gist.github.com/vamshikolanu/f367a790e0e30d47d4e69c97f754a477
> DBT-684: Add functional tests for iceberg

- tests/functional/adapter/test_grants.py
Grant tests are failing with 1.3.* of dbt core. Skipping these tests for now.
https://jira.cloudera.com/browse/DBT-679
https://gist.github.com/vamshikolanu/46ea8db4d99f5f8fc4680cf1ffabe18b
> DBT-679: Skipping grant functional tests

- dbt/adapters/impala/impl.py
- tests/functional/adapter/test_basic.py
Currently, get_columns_in_relation() fn is returning duplicate columns as it's not parsing the partition column information. Made changes to this function to handle this scenario. Also added functional tests to handle incremental partition tables. 
https://jira.cloudera.com/browse/DBT-686
Complete test run: https://gist.github.com/vamshikolanu/f24fa9d5c607fd6eb780e58c2d4b69df
TestIncrementalWithPartitionImpala verbose test run: https://gist.github.com/vamshikolanu/6b9422d3ffef8e2d6a3d15af2f3904fa
> DBT-686: Fix duplicate columns issue in get_columns_in_relation() function.

- dbt/include/impala/macros/adapters.sql
- tests/functional/adapter/test_icerberg_format.py
For iceberg partitioned table, we need to use the **_partitioned by spec_**  clause rather than **_partitioned by_**.  Also added/updated the functional test for partition by clause within format_iceberg
https://jira.cloudera.com/browse/DBT-683
Functional test run https://gist.github.com/niteshy/19532211b262eed12f45db04ffd738a2
> Support for handling iceberg partition tables 

- dbt/adapters/impala/impl.py
- dbt/include/impala/macros/insertoverwrite.sql
- tests/functional/adapter/test_basic.py
config.get() default value is not working as expected. It's returning **None** instead of taking the default value as append. Hence explicitly setting the default incremental_strategy value to append 
https://jira.cloudera.com/browse/DBT-688
basic tests: https://gist.github.com/vamshikolanu/be58a8b74b7fd2fac02e20301e892722
insert overwrite test (verbose): https://gist.github.com/vamshikolanu/7bd533a6178f836501dfb61d36ba15d5
append test (verbose): https://gist.github.com/vamshikolanu/f2ebf2a4d4a309417ae465d0ce65b76a
> DBT-688: Fix default value of incremental_strategy. 

- dbt/include/impala/macros/insertoverwrite.sql
- tests/functional/adapter/test_icerberg_format.py
Insert overwrite for iceberg tables needed a fix to the query. Added partition column to the column list while performing insert overwrite operation.
https://jira.cloudera.com/browse/DBT-689
Base tests (Regression):  https://gist.github.com/vamshikolanu/6f3aa3d7229597cd3e8c7997d4e9441a
Iceberg tests (Regression): https://gist.github.com/vamshikolanu/822fa7b781c22afe860aa5a02a210e34
Insert overwrite test (Verbose): https://gist.github.com/vamshikolanu/9a52487285fdfcbcd043f7ba462fb531
> DBT-689: Fix insert overwrite functionality for iceberg tables 

- dbt/include/impala/macros/insertoverwrite.sql
In the insert query, we don't need to provide an explicit column list. The nested select already has the column list for the insert. Removed the unused macro too
This will simplify the conditions for iceberg and other queries
https://jira.cloudera.com/browse/DBT-691
https://gist.github.com/niteshy/b2f08880496b344940a6a1b04ddb9bc9
> DBT-691: Insert queries doesn't need explicit column list

- dbt/include/impala/macros/adapters.sql
- tests/functional/adapter/test_icerberg_format.py
Rather than using a boolean flag **iceberg = true** in the configuration, we should use **table_type = "iceberg"** 
https://jira.cloudera.com/browse/DBT-692
https://gist.github.com/niteshy/3b96b876f162ab90b9c03087166a8441
> DBT-692: Renaming the iceberg flag from boolean to table_type = iceberg

- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- dev-requirements.txt
- setup.py
Adding a pre-commit hook for code quality, and formatting configurations. Actual formatting changes are part of https://github.com/cloudera/dbt-impala/pull/169. These are kept intentionally separate so that configuration can be easily reviewable. 
Formatting the code to use Python 3.7 or higher syntax 
https://jira.cloudera.com/browse/DBT-693
> DBT-693: Pre-commit checks for code quality and syntax, with python 3.7 support

- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- dev-requirements.txt
- setup.py
Adding a pre-commit hook for code quality, and formatting configurations. Actual formatting changes are part of https://github.com/cloudera/dbt-impala/pull/169. These are kept intentionally separate so that configuration can be easily reviewable.
Formatting the code to use Python 3.7 or higher syntax
https://jira.cloudera.com/browse/DBT-693
https://gist.github.com/niteshy/04e7fceeb07e06104c4bfb1ac3b055bc
> DBT-693: Pre-commit checks for code quality and syntax, for python 3.7 plus

- dbt/include/impala/macros/adapters.sql
Even though the queries ending with semicolon works for Impala without UA but they fails with ParseException in UA 
Hence, removed the ending semicolon for all queries. 
[DBT-698](https://jira.cloudera.com/browse/DBT-698)
Verified no regression in impala (without UA) https://gist.github.com/niteshy/9657cc0a52515e5f8f90b6f52a0e9541 
Verified the ParseException is fixed, but there are SemanticException https://gist.github.com/niteshy/a01837d9dc1dbbfe760e40c6df967d9c, which is separate issue [DBT-699](https://jira.cloudera.com/browse/DBT-699)
> DBT-698: Fixing the ParseException in UA, via removing the semicolon at the end of query

- tests/functional/adapter/test_basic.py
Adding tests for Incremental full refresh. As part of this test, Running full-refresh after ensuring incremental mode is working as expected. 
Full refresh does the following:
1. Create a temp table as the model query.
2. Alters the main table to temp table.
3. Alters temp table to main table.
4. Drops the renamed main table
https://jira.cloudera.com/browse/DBT-746
Create table as statement:
https://gist.github.com/vamshikolanu/302bb0b7ca9efaa75fa74c9225f65b7c#file-gistfile1-txt-L980
Alter table statements:
https://gist.github.com/vamshikolanu/302bb0b7ca9efaa75fa74c9225f65b7c#file-gistfile1-txt-L1047
https://gist.github.com/vamshikolanu/302bb0b7ca9efaa75fa74c9225f65b7c#file-gistfile1-txt-L1097
Drop table statement:
https://gist.github.com/vamshikolanu/302bb0b7ca9efaa75fa74c9225f65b7c#file- …
> DBT-746: Add tests for Incremental full refresh

- Makefile
- README.md
Added the Makefile for easy of development. Fix the version description in Readme. 
https://gist.github.com/niteshy/68f431c36116d22bc1207aab75bc1c4c
> DBT-751: Added Makefile and fix the version in Readme

- dbt/include/impala/macros/incremental.sql
Impala doesn't support the creation of temp tables. As part of this change, dropping the temp table that get part of incremental strategy
https://jira.cloudera.com/browse/DBT-750
Before - No drop table statement here: https://gist.github.com/vamshikolanu/71976afa8969b2b828abdb5f728ad1be#file-gistfile1-txt-L700
After: https://gist.github.com/vamshikolanu/6bcde91db9369a94d7d5ec94cb1d0460#file-gistfile1-txt-L700
> DBT-750: Drop temp tables create as part of incremental strategy

- dbt/adapters/impala/__version__.py
- dbt/adapters/impala/connections.py
- dbt/adapters/impala/impl.py
- setup.py
We found that during the metadata scan if the _describe_ statement one of the table(/s) is failed then the metadata information for all tables is lost. DBT assumes that none of these tables exists. This causes the models to run as a first run of an incremental strategy and try to create a table. This results in unwanted cascading errors. 
To resolve such issues, we should throw or raise the exception the first time when we see the error in the _describe_ commands. 
https://jira.cloudera.com/browse/DBT-758
https://gist.github.com/niteshy/f56c91638739b12978a5164ae310fa49
> DBT-758: Raise the exception if the metadata scan failed for any table

- dbt/adapters/impala/__version__.py
- dbt/adapters/impala/impl.py
- dbt/include/impala/macros/adapters.sql
- setup.py
Currently list_relations_without_caching function fails for all the models even if the describe statement fails for even one table in a model. 
For example: Describe statement of an iceberg table can fail if the metadata of the table is corrupted. 
This PR handles this case and logs the error making sure other models don't get effected. 
https://jira.cloudera.com/browse/DBT-759
https://gist.github.com/vamshikolanu/a3c78218b3d18e28c93458b444829b3d
> DBT-759: Handle failures of describe statement in list_relations_without_caching() function 

- .gitignore
The current .gitignore uses `.venv/` to exclude the virtual environment directory, but it seems to be ineffective in preventing the tracking of files within the .venv directory. To address this issue and ensure proper exclusion, this pull request suggests updating the .gitignore file to use the pattern `.venv*`. 
https://jira.cloudera.com/browse/DBT-761
[gitignore_gist.txt](https://gist.github.com/nsharma-25/3856b1fe131b689989f931c686c4405b#file-gitignore_gist-txt)
> DBT-761: Updating .gitignore to use .venv* instead of .venv/ for consistency

- Makefile
- dbt/adapters/impala/__version__.py
- dbt/include/impala/macros/utils/datediff.sql
- dev-requirements.txt
- setup.py
- tests/functional/adapter/test_utils.py
1. Upgrade dbt-core to 1.6
2. Removed support for microseconds datediff micro as Impala doesn't really support microseconds extration from timestamp.
3. Renamed prepare-env to dev_setup in the make file to make it consistent with dbt-hive adapter. 
https://jira.cloudera.com/browse/DBT-772
https://gist.github.com/vamshikolanu/f6f6800ce24f638d2936addf56101b82
> DBT-772: Upgrade dbt-impala adapter to use v1.6 dbt-core

- CONTRIBUTING.md
- Makefile
- dev-requirements.txt
- tox.ini
As part of this PR, Made changes to improve the performance of functional tests. The previous runtime for all the tests was around 90 mins. Now all the tests complete under 12 mins. Was able to achieve this by running tests in parallel using pytest-xdist library.
Also using this test suite, we can test the adapter for multiple versions of python using tox.
https://jira.cloudera.com/browse/DBT-781
https://gist.github.com/vamshikolanu/97f6f9d637e825fcdd0efa73a87f1c77
Individual test: https://gist.github.com/vamshikolanu/b1b12a06950e5d0b874ca2550e259760
> DBT-781: Improve the performance of functional tests.

- README.md
- dbt/adapters/impala/__version__.py
- dbt/adapters/impala/cloudera_tracking.py
- dbt/adapters/impala/column.py
- dbt/adapters/impala/connections.py
- dbt/adapters/impala/impl.py
- dev-requirements.txt
- setup.py
- tests/functional/adapter/test_concurrency.py
Upgraded dbt-impala's dbt-core dependency to 1.8.0.
https://jira.cloudera.com/browse/DBT-784
Test gist on all python versions
https://gist.github.com/niranjancdw/6d0f0ee196a8e90890194f90882d4780
> DBT-784 Fix-1.8.0-impala Support dbt-core 1.8.0 for dbt-impala
