dbt/adapters/impala/__version__.py, setup.py
Bump versions in setup.py and __version__.py to 1.0.4
=> bump versions 1.0.4

dbt/include/impala/macros/adapters.sql
Internal Ticket: https://jira.cloudera.com/browse/DBT-76
No test needed for this diff.
=> remove unsupported backup clause from create table as

dbt/include/impala/macros/seed.sql
See: Issue#17 https://github.com/cloudera/dbt-impala/issues/17
Internal Ticket: https://jira.cloudera.com/browse/DBT-78
Testplan: Please follow the steps in Issue#17
=> Fix: column types not honoured when using dbt seeds

dbt/adapters/impala/__version__.py, setup.py
Change Alpha classifier to Beta
Remove Python 3.10 classifier
Bump version in setup.py and __version__.py to 1.0.4-1
=> Update setup.py for 1.0.4b release

setup.py
Remove Python 3.10 classifier
Remove Alpha Classifier
Add Beta Classifier
=> Update setup.py for 1.0.5rc2 (first beta release)

dbt/adapters/impala/connections.py
Internal Ticket: https://jira.cloudera.com/browse/DBT-68
This is a small piece of code that will anonymously track any open connection events with the dbt-impala adapater.
The data is sent to a Cloudera controlled snowplow endpoint using simple HTTPS request. No user identifiable information is sent.
Tracking is enabled by default, to disable tracking for your project profile.yml, set usage_tracking to False.
=> usage tracking code - Cloudera specific

dbt/adapters/impala/connections.py
Internal Ticket: https://jira.cloudera.com/projects/DBT/issues/DBT-94
=> add timeout for snowplow endpoint to handle air gapped env

dbt/include/impala/macros/adapters.sql
Internal Ticket: https://jira.cloudera.com/browse/DBT-105
Test Plan:
1. Create a view materialzation model with all capital letters
2. use dbt run --select <VIEW_MODEL> to run the model. The model should be correctly created.
=> ensure lower case for pattern passed to "show tables in" query

dbt/adapters/impala/impl.py
This fix for an issue with get_catalog that caused empty catalog to be generated.
This PR depends on dbt-core 1.1 migration.
=> fix for an issue with get_catalog that caused empty catalog to be generated

dbt/adapters/impala/__version__.py, setup.py
* bump dbt-core dependency to 1.1
* bump version number to 1.1.0
=> prepare move to dbt-core 1.1

README.md, dbt/adapters/impala/__version__.py, setup.py
- update to 1.1.1 release update README for impyla 0.18a5 dependency
=> prepare for 1.1.1 release

.env_example, .gitignore, MANIFEST.in, dbt/adapters/impala/connections.py, setup.py
Internal Ticket: https://jira.cloudera.com/browse/DBT-107
Testplan:
- copy .env_example to dbt/adapters/impala/.env
- edit dbt/adapters/impala/.env and change SNOWPLOW_ENDPOINT and SNOWPLOW_API_KEY to appropriate values
- run dbt debug
- check if instrumentation data is being recoded, see ticket internal ticket (https://jira.cloudera.com/browse/DBT-68)
=> Move out the secrets for instrumentation code.

dbt/adapters/impala/connections.py
make dbname / database optional to provide in the input.
if provided, ensure dbname / database has the same value as schema.
this is because in impala schema and database are the same
Internal Ticket: https://jira.cloudera.com/browse/DBT-120
Testplan:
a) Use a profile something like below with dbt debug (only provide schema)
<pre>
dbtdemo:
target: dev_impala_ldap
outputs:
dev_impala_ldap:
type: impala
host: dbt-impala-gateway.ciadev.cna2-sx9y.cloudera.site
http_path: dbt-impala/cdp-proxy-api/impala
username: [username]
password: [password]
port: 443
auth_type: ldap
auth: LDAP
use_http_transport: true
use_ssl: true
schema: dbtdemo
threads: 1
</pre>
b) Use a profile something like below with dbt debug (provide schema and dbname with same value)
<pre>
dbtdemo:
target: dev_impala_ldap …
=> make dbname / database optional to provide in the input profiles

README.md, dbt/adapters/impala/__version__.py, setup.py
- update setup.py and __version__.py for version number
- update README to indicate correct dbt-core dependency is pulled
=> prepare for 1.1.2 release

tests/conftest.py, tests/functional/adapter/test_basic.py
To test:
0. set the secrets IMPALA_USER and IMPALA_PASSWORD
1. run the tests:
python3 -m pytest tests/functional -k 'TestBaseDocsImpala'
python3 -m pytest tests/functional -k 'TestBaseDocsGenRefsImpala'
=> integrate new basic tests

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
- refactoring usage tracking code into a separate module
- add logs for the tracking data being sent
- add logs if the tracking url throwed error
=> refactor tracking code

dbt/adapters/impala/connections.py
No logic changes. Just reformatted code and fixed typos.
dbt debug and run to test nothing has broken
=> Fix typos and refactor code to pep-8 standards

.env_example, dbt/adapters/impala/cloudera_tracking.py
- gracefully handle exceptions for tracking code
- fix a typo SNOWPLOW_ENV
=> gracefully handle exceptions for tracking code

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
With good snowplow config. 
With bad snowplow config . run still succeeds with snow plow error being logged.
=> Platform instrumentation

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
- move the version info fetch out of cloudera_tracking.py
- add the platform_info into the tracking_payload
=> refactor adapter version instrumentation 

dbt/adapters/impala/connections.py
Testplan:
In a sample DBT project, use dbt debug. 
Check logs/dbt.log for the lines similar to:
(for open)
[[0m15:09:01.849081 [debug] [Thread-1  ]: Tracker adapter: Sending Event [{"data": {"id": "dbt_impala_open", "unique_hash": "0d957f2dd9707f9eea2aa91a24858cb4", "auth": "insecure", "connection_name": "debug", "connection_state": "open", "connection_opening_time": 0.0065691471099853516}}]
(for close)
[[0m15:09:01.872359 [debug] [Thread-2  ]: Tracker adapter: Sending Event [{"data": {"id": "dbt_impala_close", "unique_hash": "0d957f2dd9707f9eea2aa91a24858cb4", "connection_name": "debug", "connection_closing_time": 0.0003440380096435547}}]
=> track connection opening and closing

dbt/adapters/impala/connections.py
capture exception object for instrumentation on connection failures.
the sample record on connection failure would look like:
<pre>
{
"data": {
"event_type": "dbt_impala_open",
"auth": "insecure",
"connection_state": "fail",
"elapsed_time": "0.00",
"connection_exception": "Could not connect to any of [('::1', 21050, 0, 0), ('127.0.0.1', 21050)]",
"python_version": "3.9.11",
"system": "Darwin",
"machine": "x86_64",
"platform": "macOS-12.6-x86_64-i386-64bit",
"dbt_version": "1.2.1",
"dbt_adapter": "impala-1.2.0",
"unique_host_hash": "421aa90e079fa326b6494f812ad13e79",
"unique_user_hash": "6adf97f83acf6453d4a6a4b1070f3754",
"unique_session_hash": "32cc89fadd1a7a2534c43eb625f29f33",
"id": "82a92a28-dbf0-474f-8faa-d5cf2b9e1aeb"
}
}
</pre>
=> for connection failures, capture the exception object for instrumentation

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
Tested that profile info appears in logs.
```
[
{
"data": {
"event_type": "dbt_impala_end_query",
"sql": "select 1 as id",
"elapsed_time": "10.42",
"status": "OK",
"profile_name": "dbt_impala_demo",
"python_version": "3.10.6",
"system": "Darwin",
"machine": "arm64",
"platform": "macOS-12.5.1-arm64-arm-64bit",
"dbt_version": "1.2.1",
"dbt_adapter": "impala-1.2.0",
"id": "7792a72d-631b-41c7-828c-eef2d8a229f4",
"unique_host_hash": "9fe1499924375e3a3d156c410bc338c4",
"unique_user_hash": "6444baa7f3e0fa703845a1ca38c973b6",
"unique_session_hash": "4d5fd37cbc18b9f8cbf3b5be4dddfe7b",
"project_name": "dbt_impala_demo",
"target_name": "dev_cia_cdp",
"no_of_threads": 1
}
}
]
```
=> Add profile related instrumentation

dbt/include/impala/macros/insertoverwrite.sql
The earlier implementation defauled to insert overwrite when partition_by clause was provided. As a result even if the incremental strategy was specified as append mode along partition_by clause, the default mode of insert overwrite was. This PR address this issue.
Internal Ticket: https://jira.cloudera.com/projects/DBT/issues/DBT-316
Testplan:
1. Clone example repo: https://github.com/cloudera/dbt-impala-example
2. Modify models/marts/covid/covid_cases.sql with the following config:
<pre>
{{
config(
materialized='incremental',
partition_by='report_date',
incremental_strategy='append'
)
}}
</pre>
3. Follow the steps in the example repo and do the first dbt run
4. Again do the second dbt run with additional data. logs/dbt.log should have the following statement generated for appends with …
=> Make partition_by work with append incremental model

dbt/adapters/impala/impl.py
Testing:
Looked at logs being sent to dbt tracker
12:44:01.213597 [debug] [Thread-6 (]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_debug_and_fetch_permissions", "permissions": "[{\"principal_type\": \"GROUP\", \"principal_name\": \"srv_dbt_demo_user\", \"database\": \"*\", \"table\": \"\", \"column\": \"\", \"uri\": \"\", \"udf\": \"*\", \"privilege\": \"all\", \"grant_option\": false, \"create_time\": null}, {\"principal_type\": \"GROUP\", \"principal_name\": \"srv_dbt_demo_user\", \"database\": \"*\", \"table\": \"*\", \"column\": \"*\", \"uri\": \"\", \"udf\": \"\", \"privilege\": \"all\", \"grant_option\": false, \"create_time\": null}]", "python_version": "3.10.6", "system": "Darwin", "machine": "arm64", "platform": "macOS-12.5.1-arm64-arm-64bit", "dbt_version": …
=> Add logic to fetch permissions for user on configured schema/database

dbt/adapters/impala/cloudera_tracking.py
Output from dbt debug to show common schema
```
05:44:42  Running with dbt=1.1.2
dbt version: 1.1.2
python version: 3.10.6
python path: /Users/tsenapati/Desktop/venvs/venv-impala/bin/python3
os info: macOS-12.5.1-arm64-arm-64bit
Using profiles.yml file at /Users/tsenapati/.dbt/profiles.yml
Using dbt_project.yml file at /Users/tsenapati/Desktop/dbt-projects/dbt-impala-example/dbt_impala_demo/dbt_project.yml
Configuration:
profiles.yml file [[32mOK found and valid[0m]
dbt_project.yml file [[32mOK found and valid[0m]
Required dependencies:
- git [[32mOK found[0m]
Connection:
host: coordinator-hb01-impala.dw-hb01-hybrid-aws.ylcu-atmi.cloudera.site
port: 443
schema: default
username: srv_dbt_demo_user
{
"event_type": "dbt_impala_start_query",
"sql": "select 1 as id",
"profile_name": …
```
=> Fix schema of tracking payload

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/impl.py
convert sql to sql_type param for instrumentation
fix a quoting issue with show grants
=> fix instrumentation artifacts

dbt/adapters/impala/impl.py
Cleanup the debug user permissions instrumentation.
* make the query consistent for dbt runs (query should succeed even when there is no schema)
* close the connection properly in case of error in grants query statement
* rename event_type to dbt_impala_debug_and_fetch_permissions
Internal: https://jira.cloudera.com/browse/DBT-396
With a dbt debug, check the output in logs/dbt.log, there should be an entry similar to:
16:39:16.207440 [debug] [Thread-6  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_impala_debug_and_fetch_permissions", "permissions": "[{\"database\": \"default\", \"table\": \"server\", \"partition\": \"[]\", \"column\": \"[]\", \"principal_name\": \"srv_dbt_demo_user\", \"principal_type\": \"USER\", \"privilege\": \"ALTER\", \"grant_option\": false, …
=> Cleanup the debug user permissions instrumentation

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
Added changes to fetch cml related instrumentation data
[Internal jira url](https://jira.cloudera.com/browse/DBT-349)
Checked on cml workspace using new code that cml data is being fetched.
=> Added code to fetch cml platform data

setup.py
update impyla dependency to stable 0.18 version
N/A
N/A
=> update impyla dependency to stable 0.18 version

dbt/adapters/impala/__version__.py, setup.py
=> Bump to version 1.1.4

setup.py
add kerberos dependency
N/A
N/A
=> add kerberos dependency

RELEASE_NOTES.md
=> updated release Notes

dbt/adapters/impala/impl.py
include warehouse version in dbt debug instrumentation
DBT-437 (Internal)
In a dbt project, for a valid dbt profile, run dbt debug. The log should contain an instrumentation event similar to:
11:10:09.140043 [debug] [Thread-6  ]: Tracker adapter: Sending Event [{"data": {"event_type": "dbt_impala_warehouse", "warehouse_version": "[{\"version()\": \"impalad version 3.4.0-SNAPSHOT RELEASE (build 341f74e07cc7cbf3610ea55cb9c30722891222a1)\\nBuilt on Fri Feb 25 11:02:19 UTC 2022\"}]", "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "4737e7bc-b017-45cc-97af-9e59566a0070", "unique_host_hash": "755624c34834153e99eb60a0d7fc07ac", …
=> [DBT-437] include warehouse version in dbt debug instrumentation

tests/conftest.py
- cleanup conftest
- move host and port number as env var
=> cleanup conftest

dbt/include/impala/macros/adapters.sql, dbt/include/impala/macros/utils/timestamps.sql
* move timestamp macro under utils
* remove timestamp macro from adapter.sql
=> refactor current_timestamp macro

dbt/include/impala/macros/utils/any_value.sql, dbt/include/impala/macros/utils/bool_or.sql, dbt/include/impala/macros/utils/hash.sql, tests/functional/adapter/test_utils.py
* add tests for: hash, cast_bool_to_text, bool_or, any_value
* implement failing macros: hash, any_value, bool_or
Run tests using:
python -m pytest tests/functional/adapter/test_utils.py -k '[test-class-name]'
=> misc cross-db functions (hash, any_value, cast_bool_to_text, bool_or)

dbt/include/impala/macros/utils/dateadd.sql, dbt/include/impala/macros/utils/datediff.sql, dbt/include/impala/macros/utils/last_day.sql, tests/functional/adapter/test_utils.py
add date cross-db macros
Run tests using:
python -m pytest tests/functional/adapter/test_utils.py -k '[test-class-name]'
=> add date related cross-db macros

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/connections.py
Adding support for instrumenting the dbt deployment environment information
Sample blob
{   "env": "cml",   "version": "1.1.17",   "description": "This runtime includes DBT upgraded packages dbt-impala=1.1.4,dbt-hive=1.1.4,dbt-spark-cde=1.1.6,dbt-spark-livy=1.1.7",   "edition": "dbt custom runtime",   "image": "test-image" }
Test Results :
From non-CML
\"system\": \"Darwin\", \"machine\": \"arm64\", \"platform\": \"macOS-12.6-arm64-arm-64bit\", \"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"impala-1.1.4\", \**"dbt_deployment_env\": \"\"**, \"project_name\": \"dbt_impala_demo\", \"target_name\": \"cloudera_cia_dbt_impala_demo\", \"no_of_threads\": 4}","created_at":"2022-10-27T09:03:16.109Z"}
From CML
glibc2.31\", \"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"impala-1.1.4\", …
=> Adding dbt deployment related instrumentation

dbt/adapters/impala/__version__.py, setup.py
=> bump version instrumentation branch

dbt/adapters/impala/__version__.py, setup.py
Bump up the version to 1.2.0. This adapter is compatible with dbt-core 1.2.2
=> Bump up release version to 1 2.0

dbt/adapters/impala/impl.py, tests/conftest.py, tests/functional/adapter/test_basic.py, tests/functional/adapter/test_docs.py
add docs tests
python -m pytest tests/functional/adapter/test_docs.py -vv -k 'TestBaseDocsGenRefsImpala'
<pre>
platform darwin -- Python 3.9.12, pytest-7.1.3, pluggy-1.0.0 -- /Users/ganesh.venkateshwara/code/venv/dev/dev-dbt-impala/bin/python
cachedir: .pytest_cache
collecting ... collected 3 items / 2 deselected / 1 selected
tests/functional/adapter/test_docs.py::TestBaseDocsGenRefsImpala::test_references PASSED [100%] …
=> add new tests for docs

RELEASE_NOTES.md
=> Updated releasenotes

dbt/adapters/impala/cloudera_tracking.py, dbt/adapters/impala/impl.py
fixes issue with nested json for:
warehouse_version
dbt_deployment_env
permissions
Perform a dbt debug and check the logs for Tracking data. Set a DBT_DEPLOYMENT_ENV and check the logs.
Sample json payload for the logs attached:
<pre>
[0m06:54:41.205206 [debug] [MainThread]: Tracker adapter: Sending Event {'data': '{"event_type": "dbt_impala_warehouse", "warehouse_version": [{"version()": "impalad version 4.0.0-SNAPSHOT RELEASE (build e8e9c674f449956419d983d20e5a4abc77b383d0)\\nBuilt on Sat May 14 07:50:13 UTC 2022"}], "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "incremental_strategy": "N/A", "model_name": "N/A", "model_type": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "493decf6-4b6b-4287-a008-fe15032f8b63", "unique_host_hash": …
=> fix issues with nested json for cloudera_tracking payload

README.md, dbt/adapters/impala/__version__.py, setup.py
* update version number
* update README to reflect dbt-core=1.3.x dependency
=> bump version for pypi release

RELEASE_NOTES.md
=> Updated notes

dbt/adapters/impala/impl.py
See https://github.com/cloudera/dbt-impala/pull/63
=> remove unused code due to PR #63

dbt/adapters/impala/connections.py
merge node_id and model_name into one key: model_name
Sample event after the merge:
<pre>
[0m06:17:48.784076 [debug] [Thread-97 ]: Tracker adapter: Sending Event {'data': '{"event_type": "model_access", "model_name": "dbtdemo.my_first_dbt_model", "model_type": "table", "incremental_strategy": "", "auth": "N/A", "connection_state": "N/A", "elapsed_time": "N/A", "permissions": "N/A", "profile_name": "N/A", "sql_type": "N/A", "id": "5fa35d4f-682e-4512-83ea-edee82d1ea5a", "unique_host_hash": "a80df3703d95f6c576ac4c680a231390", "unique_user_hash": "e8a5d78ea632435d797d3d58df650872", "unique_session_hash": "70469467afdd403a1fe051a644cf7c59", "python_version": "3.9.12", "system": "Darwin", "machine": "arm64", "platform": "macOS-13.0.1-arm64-arm-64bit", "dbt_version": "1.3.0", "dbt_adapter_type": …
=> merge node_id and model_name into one key: model_name

CONTRIBUTING.md, README.md, dev-requirements.txt, dev_requirements.txt, requirements.txt
Adding the contribution guideline, to help others onboard into the project. 
How to setup the local setup and start developing & testing the dbt-impala. 
Also, fix the dev-dependencies versions 
https://jira.cloudera.com/browse/DBT-673 
https://gist.github.com/niteshy/18d1ee91fa4cfaf01026587bc7a9eb4e 
- [Y] I have performed a self-review of my code
- [Y] I have formatted my added/modified code to follow pep-8 standards
- [] I have checked suggestions from python linter to make sure code is of good quality.
=> DBT-673: Adding the Contribution guideline and fixing the dev dependencies

tests/functional/adapter/test_icerberg_format.py
Iceberg incremental mv tests using partition by clause has typo `parition_by` rather than `partition_by`. 
Adding the tests to use multiple partition by keys  
https://jira.cloudera.com/browse/DBT-683
Test cases: https://gist.github.com/niteshy/7b5b64539516c44c172186737142b792 
Logs: https://gist.github.com/niteshy/4d320f25824a295e7be964406f5b0090 
https://gist.github.com/niteshy/82e375efaf0ee1a2aed4b21d15e118cf
=> DBT-683: Fixing typo in iceberg partition tests, adding multiple partitions tests

README.md, RELEASE_NOTES.md, dbt/adapters/impala/__version__.py, setup.py
Update Readme documentation and Release Notes for the 1.3.4 release
Update Package version for 1.3.4. 
Note: PyPI doesn't have 1.3.2 & 1.3.3, both based on the Releng these versions were released, even though no package numbers have changed.  
https://jira.cloudera.com/browse/DBT-687
Verify the integration tests: 
Python 3.7 https://gist.github.com/niteshy/f020bcb843d7a8379e1c79cf88ee5d07
=> DBT-687: v1.3.4 release version and release-notes

RELEASE_NOTES.md, dbt/adapters/impala/__version__.py, setup.py
Update package version and Release Notes 
Note: #161 have bump up the package version to 1.3.4, which is not required because release engineering take care of mapping the dbt-impala version to the given release. 
This release will be 1.3.4 but it can map to dbt-impala 1.3.2 
https://jira.cloudera.com/browse/DBT-687
Same as #161
=> DBT-687: update package versions for v1.3.2 release

dbt/adapters/impala/__version__.py, dbt/adapters/impala/connections.py, dbt/adapters/impala/impl.py, dbt/adapters/impala/relation.py, dev-requirements.txt, setup.py, tests/functional/adapter/test_utils.py
dbt-core > 1.3 ie 1.4 & 1.5 has breaking changes, hence we need to make a compatible changes for 1.4 & 1.5 
https://jira.cloudera.com/browse/DBT-704
https://gist.github.com/niteshy/56312cadf2559d8df711fdbff23fee2d
=> DBT-704: Changes required for making it compatible with dbt-core 1.4 & 1.5

dbt/adapters/impala/__version__.py, setup.py
Updating package version to 1.4.1 
N/a
=> Updating version to v1.4.1

README.md
Update the description requirements, as it is causing confusion to other folks. 
DBT-782
N/A
=> DBT-782: Update readme requirement to reflect right version

CONTRIBUTING.md, dbt/adapters/impala/connections.py, dbt/adapters/impala/impl.py, pytest.ini, tests/unit/__init__.py, tests/unit/test_exceptions.py, tox.ini
Starting dbt-core version 1.4.0, exception package has undergone multiple refactoring. Changed the old exception references to point to the correct usage. 
https://jira.cloudera.com/browse/DBT-804
https://gist.github.com/niranjancdw/a91a54c8f758b4262d9c11244925fd85
=> DBT-804 Fix-1.8.0-impala Changed obsolete exception references to correct ones
